### ISSUE TITLE
Generate monthly standardized images for instant download

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#112]
We're moving forward with the cardshop, but one of the ideas is that people shouldn't have to create an account if they only need basic content, e.g. Wikipedia, or simply see what the hotspot is like.
![Capture d’écran 2019-07-26 à 10 34 13](https://user-images.githubusercontent.com/21675885/61938294-0cb7c680-af91-11e9-9d3b-1304746b0d83.png)

The below folder has four different JSONs:
https://drive.google.com/open?id=1aey2zYUjcWVMfIzm0xkJAtWGwhGMI2yV
Wikipedia EN/DE/ES, as well as Demo. We need the four images to be created and uploaded to https://download.kiwix.org/hotspots/ and the corresponding torrent links generated (so that it's easier for people to download)

**Comment by rgaudin** [comment]
Good! For that to be interesting, we need to refresh those images frequently (to include the latest ZIMs) – monthly once the zimfarm is up and running with those large ZIMs.

Questions:

* this only applies to downloadable images right? No SD-card involved?
* How do you charge for a torrent?

If we're to charge for those files, I assume those won't be just publicly available on our download server/mirrors?

Our cardshop images are currently only _protected_ by their link not being shared anywhere but in the confirmation email. We allow and encourage sharing the link because it's a unique configuration and the file is gone after a week.

In this new scenario, image files won't move and there's incentive in sharing the links. 

We can _control/restrict_ download for an HTTP link but for a torrent?

So the question is how much do we want to enforce the payment of those images given protection measures are effort consuming? Common-sense would lean on trusting fair-use until it's abused.

**Comment by Popolechien** [comment]
``this only applies to downloadable images right? No SD-card involved?``
Correct

``How do you charge for a torrent?``
The wordpress widget will send a confirmation email. We'll include the link in the email, and either generate a new torrent every month, or accept that some smart freeriders will order once and reuse old links for free in the future (if that was your question).

``If we're to charge for those files, I assume those won't be just publicly available on our download server/mirrors?``
That was a question I had. Can we host the images (except the demo one) on non-publicly available folders (meaning that someone browsing download.kiwix.org will find a folder they can't open)? 

I agree with you that we'll have to trust users fairness for the time being and then figure things out when some smartass decides they won't pay their share of the effort and abuse the system. Is there a way to monitor the number of times a specific file is downloaded, so as to compare it with the number of payments we got?
