### ISSUE TITLE
Cardshop has failed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#125]
Log:

Starting to work on 5d5ea62198c8bff693fcc58b
updating task #5d5ea62198c8bff693fcc58b status to: building
Starting image creation
Starting /usr/bin/kiwix-hotspot cli --root --filename 5d5ea61f98c8bff693fcc566 --build-dir /data --config /data/5d5ea61f98c8bff693fcc566.json --size 64GB

installer started: <subprocess.Popen object at 0x7f0371d60908>
installer failed: 1
collecting full terminated log
installer rc: 1
Traceback (most recent call last):
  File "worker/tasks/create.py", line 103, in run
    getattr(self, method)()
  File "worker/tasks/create.py", line 188, in build_image
    raise subprocess.SubprocessError("installer rc: {}".format(ps.returncode))
subprocess.SubprocessError: installer rc: 1
updating task #5d5ea62198c8bff693fcc58b status to: failed_to_build
job is not alive
job crashed: installer rc: 1

**Comment by rgaudin** [comment]
Thanks for the report but please make it more useful:

* proper title (so we can assess emergency)
* order-id (so it can be found easily)
* reason for the crash if known.

Here's it's a card creation (installer) error and the (linked) log says 
```
Error while parsing your config file (/data/5d5ea61f98c8bff693fcc566.json)
Incorrect values for `zim_install`: education-et-numerique_fr.fr
```
I know you are used to provide all this information 🤓

So the problem is that the cardshop library is not in sync with the installer one.
I am restarting the manager for that to happen. We're waiting for some features on OPDS backend to switch both the installer and the cardshop to OPDS and not care about those anymore.

**Comment by Popolechien** [comment]
@rgaudin Ah sorry, the bane of doing three things at the same time :-(
