### ISSUE TITLE
Order L136R5D71 has failed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#134]
Looks similar to  #133, no?

Log:
Starting to work on 5d71027e98c8bfdf6cfced22
updating task #5d71027e98c8bfdf6cfced22 status to: building
Starting image creation
Starting /usr/bin/kiwix-hotspot cli --root --filename 5d71027c98c8bfdf6cfcecfd --build-dir /data --config /data/5d71027c98c8bfdf6cfcecfd.json --size 64GB

installer started: <subprocess.Popen object at 0x7ff5b2946dd8>
periodic log upload..................
sending logs for task #5d71027e98c8bfdf6cfced22.
periodic log upload..................
sending logs for task #5d71027e98c8bfdf6cfced22.
periodic log upload..................
sending logs for task #5d71027e98c8bfdf6cfced22.
periodic log upload..................
sending logs for task #5d71027e98c8bfdf6cfced22.
installer failed: 0
collecting full terminated log
installer rc: 0
Traceback (most recent call last):
  File "worker/tasks/create.py", line 103, in run
    getattr(self, method)()
  File "worker/tasks/create.py", line 188, in build_image
    raise subprocess.SubprocessError("installer rc: {}".format(ps.returncode))
subprocess.SubprocessError: installer rc: 0
updating task #5d71027e98c8bfdf6cfced22 status to: failed_to_build
job is not alive
job crashed: installer rc: 0

**Comment by rgaudin** [comment]
You're right, it's similar but it's actually an edge case. We're getting the actual filename from the progress output and this file is so small (17MiB) that it gets downloaded before displaying our periodic progress (every second).

I'll let you know once I have fixed, deployed and sucessfully generated a copy of that config.

**Comment by rgaudin** [comment]
Done.

**Comment by Popolechien** [comment]
Uh, I just restarted the order and got the same failure. Did I go to fast and the fix hasn't been rolled out yet?

**Comment by rgaudin** [comment]
Yes, it's very similar and no you weren't too fast ; I had already deployed and tested before closing the issue. The installer shows it ran with installer 2.1.1, the expected version.

I launched a new order (`L139R5D72`) with an identical build except it outputs tons of logs. It passed the download step, as my previous step so I think we might be chasing an edge case (on a specific mirror). We'll use this build until we run into this issue again but now we'll have better logs to find-out what happens when it fails.

I suggest you wait for that build to safely complete and maybe retry the client one.
