### ISSUE TITLE
Cardshop wrongfully sends failed order message when account is closed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#170]
I just closed an account whose order had been delivered but remained within the bounds of the D+7 download window. The cardshop sent a wrongful/misleading fail message to the user (file is still available for download).

Since we control account closures, I would recommend refraining from sharing this kind of automated communication.

**Comment by rgaudin** [comment]
Can you share the sent message?

**Comment by Popolechien** [comment]
Here we go (edited names out). Really the usual fail message.

![Capture d’écran 2020-08-28 à 10 40 39](https://user-images.githubusercontent.com/21675885/91540481-27d6d180-e91b-11ea-8958-eefa2d816624.png)

**Comment by rgaudin** [comment]
OK I get it, the order is not complete because it's a download one and (although the person downloaded it – but we cannot know that) it hasn't reached the 7d period.
So whenever we're deleting an account, we're canceling any incomplete order, thus triggering that email.

As already discussed, this use case of creating an account for a specific order is a workaround the user model that we currently have and want to change.

I don't think it's pertinent to handle this use case as the use case should go away (we already have tickets for this).
In the mean time, you could just wait for the end of the period before deleting the account.

**Comment by Popolechien** [comment]
Sounds good to me. Thanks.
