### ISSUE TITLE
healtcheck is slightly too slow

### ISSUE THREAD

**Issue by kelson42** [kiwix/cardshop#226]
... and monitoring complains wrongly time to time because the HTTP response does not come quickly enough

**Comment by rgaudin** [comment]
I wouldn't invest much time before we change our infrastructure as I have a hunch this is sloppy related. I haven't been able to get this page to genuinely return after 30s (the code times out the tests before that) yet uptime robot reports `502 Bad gateway` response indicating sloppy's proxy gave up.

**Comment by kelson42** [comment]
@rgaudin OK, fine to me, as long as the monitoring does not report falsy.

**Comment by kelson42** [comment]
@rgaudin Please try to make a S3 timeout of 20 seconds.

**Comment by rgaudin** [comment]
Should be OK from now on. Had to increase uwsgi socket timeout and our-nginx to socket timeout as well. Was able to test sloppy's nginx timeout and it is set at 30s sharp. When hit by sloppy's timeout, HTTP response code is 504 so that would be visible from the monitor. 502 was thrown by our own nginx.

Increased wasabi timeout to 25s.
