### ISSUE TITLE
Card size calculation should be consistent and include OS size (and a bit of margin/no decimal?)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#24]
I have a 126 Gb config that requires a 200Gb card and a 63.97 Gb card (in the content manager) that shows 64.61 Gb (in the config manager) that needs a 128 Gb card.
![capture d ecran 2018-10-17 a 11 59 05](https://user-images.githubusercontent.com/21675885/47078741-3ecb1980-d204-11e8-9c22-28bb8ef91b43.png)

**Comment by rgaudin** [comment]
* It already includes OS size and margin (although it's underestimated ATM and will be fixed to match the Desktop version)
* Actual size (decimal) is important I think ; especially when filling-up cards completely.
* Confusion comes from the difference between SD sizes in GB and Content sizes in GiB.
* Available space on SD card is different than labels and margins.
* We have to use GB for SD sizes as it's what physical cards are labeled with.
* For content, we use GiB because that's the sizes used in computer's UI.

Maybe we should add (in the config editor, not here) a *Free Space* indication (in GiB) that would help users understand exactly how much content they can squeeze-in (especially given content sizes are in GiB)

**Comment by Popolechien** [comment]
Yes.
