### ISSUE TITLE
Creation fails with [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#249]
Order https://cardshop.hotspot.kiwix.org/orders/f/6085b5c298c8bf54df255ebe was created first and failed. I cannot, however, access the log (`Order with Scheduler ID 6085b5c298c8bf54df255ebe not found`). It also is not listed in the silo's order summary list but I can see it in the admin order list

Then orders https://cardshop.hotspot.kiwix.org/orders/L523R6085, https://cardshop.hotspot.kiwix.org/orders/L522R6085 were next in line but failed with `[Errno 12] Cannot allocate memory`

**Comment by rgaudin** [comment]
Unfortunately we didn't get the worker log and the worker has been restarted has it got updated since.
Please re-open if this ever occurs again.

I believe this was linked to the super-extra verbose logs or aria2 and the dates matches for the two occurrences of this error ; both of which in the evening of 2021-04-25, and both for very large cards.

- https://cardshop.hotspot.kiwix.org/all-orders/6085b60798c8bf54df255f0b
- https://cardshop.hotspot.kiwix.org/all-orders/6085b5c298c8bf54df255ebe

@Popolechien did this Orange card got created afterwards? It seems like both are very similar and were launched at the same time.

**Comment by Popolechien** [comment]
@rgaudin Yes it was created afterwards, but I agree it may have been unfortunate timing (restarted since and it completed fine)
