### ISSUE TITLE
Error while saving / ordering from previous configuration

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#49]
Tried to resend a previously generated order/config to a different address and got a "Error while saving - Response Error (no JSON)" when pushing  "order now"
![capture d ecran 2019-01-24 a 09 43 05](https://user-images.githubusercontent.com/21675885/51665783-daff7c00-1fbc-11e9-9338-aa18f0b1e169.png)

**Comment by rgaudin** [comment]
OK, I see that you probably retried and it worked. Verified it's working now.

it might have been because I did not initiate any action with the scheduler after deploying the containers and thus the manager's token might have needed a refresh.

I'm closing this but please reopen if something similar happens again.
