### ISSUE TITLE
Communicate about image creation duration

### ISSUE THREAD

**Issue by Popolechien** [kiwix/cardshop#92]
It might be useful in terms of UX to give people an estimate of when the image they ordered will be ready. The simpler way would be to attach a value to each card size (e.g. 32 Gb = 30 minutes; 128 gb = 4 hours), but should we expect major variations based on content (e.g. 32 Gb made with 20 zims will take longer than 32 Gb with 2 zims, all other things being equal)?

Which parameters would influence creation time?
- number of zims?
- size of each individual zim?
- current queue?
- ?

**Comment by rgaudin** [comment]
hum, not sure we’ll be able to give a useful estimate.

We could build a rough estimate of image creation duration (it depends on
non-zim contents) but we there’s also the queue (we could approximate this
based on previous) and upload duration (we could approximate but it’s
likely to vary).

that’s for downloadable images. it’s already too much approximation layers
to me. I’m afraid giving a poor info is worst than no info.
And we are already sending emails (maybe not to user ATM) at the end of
each step.

For physical cards, there’s too much uncertainty I think (delay to remove,
delay to download, delay to insert, shipping)

@kelson42, opinion ?

**Comment by Popolechien** [comment]
Yep, physical cards are too far out our realm of control. I would exclude queueing time (or replace with "your order is number X in queue, after that it'll need Y hours to complete"), but how come the upload duration is likely to vary significantly from one card creation to the other?

**Comment by kelson42** [comment]
@Popolechien @rgaudin I would just say, if you don't get an email in N days that the image is ready, please contact us.

**Comment by rgaudin** [comment]
> how come the upload duration is likely to vary significantly from one card creation to the other?

Because it's gigabytes of transfers between servers on data centers. So the regular rate is very high but any other download/upload on either of the servers would dramatically reduce the available bandwidth.

Say you're uploading 128GB from demo server to warehouse, if both are network-idle, it may start at 100Mbps. Then during this upload, a zimfarm worker starts to upload a large ZIM. If download capacity of the warehouse (bandwidth + write speed) is 100Mbps, both transfers would drop to 50Mbps.

Other factors (like load) may reduce the server's capacity to transfer data. On the previous server, it was common to start fast and quickly drop to few mbps.

We could use a conservative average and calculate from that but as for the rest, it leads to one question: what information do we want to provide? An estimate or a delay after which something's probably gone wrong?

**Comment by Popolechien** [comment]
> what information do we want to provide?
It's more around managing expectations - at this stage, users won't know if they should wait for a minute or a day before worrying something has gone astray. I guess a generic message "If you haven't heard back within 24 hours, contact support" would work (though 24 hrs is too long imho, but that's another discussion I guess)

**Comment by rgaudin** [comment]
OK, could you prepare sample messages (to include in emails) for both methods (download and physical cards) ?

**Comment by Popolechien** [comment]
> Download

Dear [user],
Your [size] download order with the [xyz] configuration on it has been accepted by the system. Word duration varies depending on the number of existing jobs and server load, but should be ready within 24 hours at most.

You will be notified when it is ready for download.

> Shipment

Current message (10 days) seems ok.

**Comment by Popolechien** [comment]
*edited text for clarity / typos

**Comment by rgaudin** [comment]
👍
